#  Copyright (c) 2025 OpenHW Group
#  Copyright (c) 2025 Thales DIS France SAS
#  SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#  Author: Jean-Roch COULON -  Thales

CONFIG := cv32a60x
include ../../design/build.mk
