# Copyright 2022 Thales Silicon Security
# Copyright 2026 Thales France
#
# Licensed under the Solderpad Hardware Licence, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
# You may obtain a copy of the License at https://solderpad.org/licenses/
#
# Original Author: Yannick Casamatta (yannick.casamatta@thalesgroup.com)

# Please refer to .gitlab-ci/README.md to add jobs

workflow:
  rules:
    - if:
        $CI_PIPELINE_SOURCE == "web"
        # CI_KIND need to be set in web interface
    - if: $CI_PIPELINE_SOURCE == "schedule"
      variables:
        CI_KIND: verif
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        CI_KIND: dev
    - if: $CI_PIPELINE_SOURCE == "/.*_PR_.*/"
      variables:
        CI_KIND: dev
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH =~ /^dev.*/
      variables:
        CI_KIND: dev
    - when: never

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"
  CONFIG_DIR: "flows/config" #should be overloaded in gitlab CI project variables section
  TERM: xterm-256color
  FORCE_COLOR: "1"
  COLUMNS: 180
  MY_SIMULATOR: vcs
  #PYTHONUNBEFFERED: "1"

stages:
  - build
  - lint
  - soft
  - rtl
  - benchmark
  - testlist
  - synth
  - report

.global_matrix_target:
  parallel:
    matrix:
      # OBI noPMP noMMU
      - MY_TARGET: cv32a60x
      - MY_TARGET: cv32a60x_no_zcmt
      - MY_TARGET: cv32a65x_noPMP
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_nopmp_nommu_obi
      # AXI noPMP noMMU
      - MY_TARGET: cv32a60x_axi
      - MY_TARGET: cv32a60x_no_zcmt_axi
      - MY_TARGET: cv32a65x_noPMP_axi
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_nopmp_nommu_axi
      # OBI PMP noMMU
      - MY_TARGET: cv32a60x_zcmt_pmp
      - MY_TARGET: cv32a65x
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_pmp_nommu_obi
      # AXI PMP noMMU
      - MY_TARGET: cv32a60x_zcmt_pmp_axi
      - MY_TARGET: cv32a65x_axi
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_pmp_nommu_axi
      # OBI PMP MMU
      - MY_TARGET: cv32a6_imac_sv32_obi
      - MY_TARGET: cv32a65x_sv32
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_pmp_mmu_obi
      # AXI PMP MMU
      - MY_TARGET: cv32a6_imac_sv32
      - MY_TARGET: cv32a65x_sv32_axi
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_pmp_mmu_axi

# Used to perform mapping 1:1 in jobs dependencies ("needs" in gitlab-ci)
.global_matrix_mapping: &global_matrix_mapping
  parallel:
    matrix:
      - MY_TARGET: ["$[[ matrix.MY_TARGET ]]"]

.rules_verif:
  rules:
    - if: $CI_KIND == "verif"
    - when: manual
      allow_failure: true

.rules_verif_regress:
  rules:
    - if: $CI_KIND == "verif"
    - if: $CI_KIND == "regress"
    - when: manual
      allow_failure: true

.rules_verif_regress_dev:
  rules:
    - if: $CI_KIND == "verif"
    - if: $CI_KIND == "regress"
    - if: $CI_KIND == "dev"
    - when: manual
      allow_failure: true

# ==========================================================
# ENV
# ==========================================================

before_script:
  - source $CONFIG_DIR/setenv.sh

.need_spike:
  before_script:
    - source $CONFIG_DIR/setenv.sh
    - mkdir tools/
    - export SPIKE_INSTALL_DIR=$SPIKE_PATH/$(git -C verif/core-v-verif/ log -1 --pretty=tformat:%h --abbrev=8)/spike
    - ln -sfn $SPIKE_INSTALL_DIR/ tools/

build_env:
  stage: build
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .rules_verif_regress_dev
  script:
    - id
    - pip3 install -r flows/requirements.txt

build_spike:
  stage: build
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .rules_verif_regress_dev
  needs: []
  script:
    - echo NUMJOB=$NUM_JOBS
    - source $SYN_VCS_BASHRC
    - "export ROOT_PROJECT=$(pwd)"
    - mkdir tools/
    - SPIKE_INSTALL_DIR=$SPIKE_PATH/$(git -C verif/core-v-verif/ log -1 --pretty=tformat:%h --abbrev=8)/spike/
      source verif/regress/install-spike.sh

# ==========================================================
# LINT
# ==========================================================

verible:
  stage: lint
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .rules_verif_regress_dev
  needs: []
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - export PATH="$VERIBLE_PATH:$PATH"
    - ./cook.py verible-rtl-formating -t cv32a60x # today target is not really important
    - git diff --name-only | tee verible-filename.log
    - git diff --color | tee verible-git-diff.log
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/cv32a60x/verible/verible-cmd.log
      - verible-git-diff.txt
      - verible-filename.txt

black:
  stage: lint
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .rules_verif_regress_dev
  needs: []
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - ./cook.py black-python-formating | tee black-cmd.log
    - git diff --name-only | tee black-filename.log
    - git diff --color | tee black-git-diff.log
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - black-cmd.log
      - black-git-diff.txt
      - black-filename.txt

pylint:
  stage: lint
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .rules_verif_regress_dev
  needs: []
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - ./cook.py pylint-run | tee pylint-cmd.log
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - pylint-cmd.log

lint_spyglass:
  stage: lint
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .rules_verif_regress_dev
    - .global_matrix_target
  needs: []
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - source $SYN_SG_BASHRC
    - ./cook.py spyglass-design-read -t $MY_TARGET
    - ./cook.py spyglass-run -t $MY_TARGET
    # Report
    - export MY_CVA6_HIER=obi #TOBEFIXED for AXI
    - python3 .gitlab-ci/scripts/report_spyglass_lint.py
      config/target/$MY_TARGET/expected_spyglass.rpt
      build/$MY_TARGET/spyglass/sg_run_results/cva6_example_${MY_CVA6_HIER}_sg_reports/cva6_example_${MY_CVA6_HIER}_lint_lint_rtl/summary.rpt
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/spyglass/*.log
      - build/$MY_TARGET/spyglass/sg_run_results
      - build/$MY_TARGET/spyglass/sg_setup

# ==========================================================
# TOOLCHAIN COMPILATION
# ==========================================================

sw_compile:
  stage: soft
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .rules_verif_regress_dev
    - .global_matrix_target
  needs: []
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - ./cook.py hello-world -t $MY_TARGET -c my_${MY_TARGET}_toolchain
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/compile/hello-world/*

# ==========================================================
# SPIKE SIMULATIONS
# ==========================================================

run_sim_spike:
  stage: soft
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .need_spike
    - .rules_verif_regress_dev
    - .global_matrix_target
  needs:
    - job: build_spike
      artifacts: true
    - job: sw_compile
      artifacts: true
      <<: *global_matrix_mapping
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - ./cook.py spike-run -t $MY_TARGET -n hello-world
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/simulation/sim_spike/hello-world

# ==========================================================
# VCS UVM RTL SIMULATIONS
# ==========================================================

elab_rtl:
  stage: rtl
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .need_spike
    - .rules_verif_regress_dev
    - .global_matrix_target
  needs:
    - job: build_spike
      artifacts: true
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - source $SYN_VCS_BASHRC
    - ./cook.py vcs-uvm-comp -t $MY_TARGET --comp-mode rtl --tandem-enabled
      --trace-mode notrace
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/elab/sim_rtl/simv
      - build/$MY_TARGET/elab/sim_rtl/simv.daidir
      - build/$MY_TARGET/elab/sim_rtl/simv.vdb
      - build/$MY_TARGET/elab/sim_rtl/compilation.log

run_sim_rtl:
  stage: rtl
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .need_spike
    - .rules_verif_regress_dev
    - .global_matrix_target
  needs:
    - job: build_spike
      artifacts: true
    - job: elab_rtl
      artifacts: true
      <<: *global_matrix_mapping
    - job: sw_compile
      artifacts: true
      <<: *global_matrix_mapping
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - source $SYN_VCS_BASHRC
    - ./cook.py vcs-uvm-run -t $MY_TARGET -n hello-world --comp-mode rtl --tandem-enabled
      --tb-performance-mode --trace-mode notrace
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/simulation/sim_rtl/hello-world

# ==========================================================
# POST SYNTHESIS SIMULATIONS (ASIC)
# ==========================================================

.asic_synthesis:
  stage: synth
  tags: [$TAGS_RUNNER_SYNTH]
  extends:
    - .rules_verif_regress_dev
    - .global_matrix_target
  needs:
    - job: elab_rtl
      artifacts: false
      <<: *global_matrix_mapping
  variables:
    MY_SYNTH_PERIOD: 15
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - source $SYN_DCSHELL_BASHRC
    - ./cook.py dc-shell-synth -t $MY_TARGET --techno $MY_TECHNO --period $MY_SYNTH_PERIOD
    - ./cook.py report-dc-shell-synth-kpi --target $MY_TARGET
    - ./cook.py report-dc-shell-synth-graph
      --target $MY_TARGET
      --top cva6
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/synthesis_base/synthesis.log
      - build/$MY_TARGET/synthesis/synthesis.log
      - build/$MY_TARGET/synthesis/Flist.libverilog
      - build/$MY_TARGET/synthesis/reports
      - build/$MY_TARGET/synthesis/netlist

.asic_synthesis_elab:
  stage: synth
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .need_spike
    - .rules_verif_regress_dev
    - .global_matrix_target
  needs:
    - job: build_spike
      artifacts: true
    - job: asic_synthesis
      artifacts: true
      <<: *global_matrix_mapping
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - source $SYN_VCS_BASHRC
    - ./cook.py vcs-uvm-comp -t $MY_TARGET --comp-mode gate_wc_timing
      --tandem-enabled --trace-mode notrace
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/elab/sim_gate_wc_timing/simv
      - build/$MY_TARGET/elab/sim_gate_wc_timing/simv.daidir
      - build/$MY_TARGET/elab/sim_gate_wc_timing/simv.vdb
      - build/$MY_TARGET/elab/sim_gate_wc_timing/compilation.log

.asic_synthesis_run_sim:
  stage: synth
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .need_spike
    - .rules_verif_regress_dev
    - .global_matrix_target
  needs:
    - job: build_spike
      artifacts: true
    - job: asic_synthesis_elab
      artifacts: true
      <<: *global_matrix_mapping
    - job: sw_compile
      artifacts: true
      <<: *global_matrix_mapping
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - source $SYN_VCS_BASHRC
    - ./cook.py vcs-uvm-run -t $MY_TARGET -n hello-world --comp-mode gate_wc_timing
      --no-tandem-enabled --no-tb-performance-mode --trace-mode notrace
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/simulation/sim_gate_wc_timing/hello-world

# ==========================================================
# BENCHMARK
# ==========================================================

.benchmark_matrix_target:
  parallel:
    matrix:
      - MY_TARGET: cv32a60x
        MY_BENCHMARK:
          - coremark
          - dhrystone
      - MY_TARGET: cv32a65x
        MY_BENCHMARK:
          - coremark
          - dhrystone

# Used to perform mapping 1:1 in jobs dependencies ("needs" in gitlab-ci)
.benchmark_matrix_mapping: &benchmark_matrix_mapping
  parallel:
    matrix:
      - MY_TARGET: ["$[[ matrix.MY_TARGET ]]"]
        MY_BENCHMARK: ["$[[ matrix.MY_BENCHMARK ]]"]

benchmark_compile:
  stage: benchmark
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .rules_verif_regress_dev
    - .benchmark_matrix_target
  needs: []
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - verif/regress/install-riscv-tests.sh
    - ./cook.py $MY_BENCHMARK -t $MY_TARGET -c my_${MY_TARGET}_toolchain
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/compile/${MY_BENCHMARK}/*

benchmark_run_sim_rtl:
  stage: benchmark
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .need_spike
    - .rules_verif_regress_dev
    - .benchmark_matrix_target
  needs:
    - job: build_spike
      artifacts: true
    - job: elab_rtl
      artifacts: true
      <<: *global_matrix_mapping
    - job: benchmark_compile
      artifacts: true
      <<: *benchmark_matrix_mapping
  allow_failure: true
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - source $SYN_VCS_BASHRC
    - ./cook.py vcs-uvm-run -t $MY_TARGET -n $MY_BENCHMARK --comp-mode rtl
      --tandem-enabled --tb-performance-mode --trace-mode notrace
    - ./cook.py report-benchmark -t $MY_TARGET -n $MY_BENCHMARK --comp-mode rtl
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/simulation/sim_rtl/${MY_BENCHMARK}/*

# ==========================================================
# TESTLIST REGRESSION (SPIKE TANDEM)
# ==========================================================

.testlist_matrix_target:
  parallel:
    matrix:
      # OBI noPMP noMMU
      - MY_TARGET: cv32a60x
        MY_TESTLIST:
          - base_rv32_p
          - base_zcmt
      - MY_TARGET: cv32a60x_no_zcmt
        MY_TESTLIST:
          - base_rv32_p
      - MY_TARGET: cv32a65x_noPMP
        MY_TESTLIST:
          - base_rv32_p
          - base_zcmt
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_nopmp_nommu_obi
        MY_TESTLIST:
          - base_rv64_p
          - base_zcmt
      # AXI noPMP noMMU
      - MY_TARGET: cv32a60x_axi
        MY_TESTLIST:
          - base_rv32_p
          - base_zcmt
      - MY_TARGET: cv32a60x_no_zcmt_axi
        MY_TESTLIST:
          - base_rv32_p
      - MY_TARGET: cv32a65x_noPMP_axi
        MY_TESTLIST:
          - base_rv32_p
          - base_zcmt
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_nopmp_nommu_axi
        MY_TESTLIST:
          - base_rv64_p
      # OBI PMP noMMU
      - MY_TARGET: cv32a60x_zcmt_pmp
        MY_TESTLIST:
          - base_rv32_p
          - base_zcmt
          - base_pmp
      - MY_TARGET: cv32a65x
        MY_TESTLIST:
          - base_rv32_p
          - base_zcmt
          - base_pmp
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_pmp_nommu_obi
        MY_TESTLIST:
          - base_rv64_p
          - base_zcmt
          - base_pmp
          - base_rv64_amo_p
      # AXI PMP noMMU
      - MY_TARGET: cv32a60x_zcmt_pmp_axi
        MY_TESTLIST:
          - base_rv32_p
          - base_zcmt
          - base_pmp
      - MY_TARGET: cv32a65x_axi
        MY_TESTLIST:
          - base_rv32_p
          - base_zcmt
          - base_pmp
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_pmp_nommu_axi
        MY_TESTLIST:
          - base_rv64_p
          - base_zcmt
          - base_pmp
          - base_rv64_amo_p
      # OBI PMP MMU
      - MY_TARGET: cv32a6_imac_sv32_obi
        MY_TESTLIST:
          - base_rv32_p
          - base_rv32_v
          - base_pmp
          - base_rv32_amo_p
          - base_rv32_amo_v
      - MY_TARGET: cv32a65x_sv32
        MY_TESTLIST:
          - base_rv32_p
          - base_rv32_v
          - base_pmp
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_pmp_mmu_obi
        MY_TESTLIST:
          - base_rv64_p
          - base_rv64_v
          - base_pmp
          - base_rv64_amo_p
          - base_rv64_amo_v
      # AXI PMP MMU
      - MY_TARGET: cv32a6_imac_sv32
        MY_TESTLIST:
          - base_rv32_p
          - base_rv32_v
          - base_pmp
          - base_rv32_amo_p
          - base_rv32_amo_v
      - MY_TARGET: cv32a65x_sv32_axi
        MY_TESTLIST:
          - base_rv32_p
          - base_rv32_v
          - base_pmp
      - MY_TARGET: cv64a6_imafdc_sv39_hpdcache_pmp_mmu_axi
        MY_TESTLIST:
          - base_rv64_p
          - base_rv64_v
          - base_pmp
          - base_rv64_amo_p
          - base_rv64_amo_v

# Used to perform mapping 1:1 in jobs dependencies ("needs" in gitlab-ci)
.testlist_matrix_mapping: &testlist_matrix_mapping
  parallel:
    matrix:
      - MY_TARGET: ["$[[ matrix.MY_TARGET ]]"]
        MY_TESTLIST: ["$[[ matrix.MY_TESTLIST ]]"]

testlist_compile:
  stage: testlist
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .rules_verif_regress_dev
    - .testlist_matrix_target
  needs: []
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - verif/regress/install-riscv-tests.sh
    - ./cook.py sw-compile-testlist -t $MY_TARGET -c my_${MY_TARGET}_toolchain -l verif/tests/${MY_TESTLIST}.yaml
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/compile/*

testlist_run_sim_rtl:
  stage: testlist
  tags: [$TAGS_RUNNER_SIMU]
  extends:
    - .need_spike
    - .rules_verif_regress_dev
    - .testlist_matrix_target
  needs:
    - job: build_spike
      artifacts: true
    - job: elab_rtl
      artifacts: true
      <<: *global_matrix_mapping
    - job: testlist_compile
      artifacts: true
      <<: *testlist_matrix_mapping
  script:
    - python3 .gitlab-ci/scripts/report_fail.py
    - source $SYN_VCS_BASHRC
    - ./cook.py uvm-run-testlist --simulator ${MY_SIMULATOR} -t $MY_TARGET -l verif/tests/${MY_TESTLIST}.yaml --comp-mode rtl
      --tandem-enabled --tb-performance-mode --trace-mode notrace
    - python3 .gitlab-ci/scripts/report_pass.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/report_*.yml
      - build/$MY_TARGET/simulation/sim_rtl/*

# ============================================================
# DASHBOARD GENERATION
# ============================================================

merge reports:
  stage: report
  tags: [$TAGS_RUNNER_SIMU]
  variables:
    GIT_SUBMODULE_STRATEGY: none
  extends:
    - .rules_verif_regress_dev
  when: always
  script:
    - mkdir -p build/
    - python3 .gitlab-ci/scripts/merge_job_reports.py
  artifacts:
    when: always
    paths:
      - artifacts/reports/pipeline_report_${CI_PIPELINE_ID}.yml
