# Configuration file for ReadTheDocs, used to render the
# Verification Strategy to https://docs.openhwgroup.org/projects/core-v-verif.
# SPDX-License-Identifier:Apache-2.0 WITH SHL-2.0

version: 2

#build:
#  os: "ubuntu-20.04"
#  tools:
#    python: "3.9"

# Build from the docs/VerifStrat/source directory with Sphinx
sphinx:
  configuration: docs/VerifStrat/source/conf.py

# Explicitly set the Python requirements
python:
  install:
    - requirements: docs/VerifStrat/requirements.txt
