// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module trigger_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic
) (
  input clk_i,
  input rst_ni,

  // Below Register interface can be changed
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output trigger_reg_pkg::trigger_reg2hw_t reg2hw, // Write
  input  trigger_reg_pkg::trigger_hw2reg_t hw2reg, // Read

  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import trigger_reg_pkg::* ;

  localparam int AW = 4;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;

  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;

  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err ;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] gpio_o_qs;
  logic gpio_o_re;
  logic ctrl_start_wd;
  logic ctrl_start_we;
  logic ctrl_stop_wd;
  logic ctrl_stop_we;
  logic status_qs;
  logic status_re;

  // Register instances

  // Subregister 0 of Multireg gpio_o
  // R[gpio_o]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_gpio_o (
    .re     (gpio_o_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.gpio_o[0].d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (gpio_o_qs)
  );


  // R[ctrl]: V(True)

  //   F[start]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_start (
    .re     (1'b0),
    .we     (ctrl_start_we),
    .wd     (ctrl_start_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl.start.qe),
    .q      (reg2hw.ctrl.start.q ),
    .qs     ()
  );


  //   F[stop]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_stop (
    .re     (1'b0),
    .we     (ctrl_stop_we),
    .wd     (ctrl_stop_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl.stop.qe),
    .q      (reg2hw.ctrl.stop.q ),
    .qs     ()
  );


  // R[status]: V(True)

  prim_subreg_ext #(
    .DW    (1)
  ) u_status (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (status_qs)
  );




  logic [2:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == TRIGGER_GPIO_O_OFFSET);
    addr_hit[1] = (reg_addr == TRIGGER_CTRL_OFFSET);
    addr_hit[2] = (reg_addr == TRIGGER_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = 1'b0;
    if (addr_hit[0] && reg_we && (TRIGGER_PERMIT[0] != (TRIGGER_PERMIT[0] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[1] && reg_we && (TRIGGER_PERMIT[1] != (TRIGGER_PERMIT[1] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[2] && reg_we && (TRIGGER_PERMIT[2] != (TRIGGER_PERMIT[2] & reg_be))) wr_err = 1'b1 ;
  end

  assign gpio_o_re = addr_hit[0] && reg_re;

  assign ctrl_start_we = addr_hit[1] & reg_we & ~wr_err;
  assign ctrl_start_wd = reg_wdata[0];

  assign ctrl_stop_we = addr_hit[1] & reg_we & ~wr_err;
  assign ctrl_stop_wd = reg_wdata[1];

  assign status_re = addr_hit[2] && reg_re;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = gpio_o_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = '0;
        reg_rdata_next[1] = '0;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = status_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Assertions for Register Interface

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))


endmodule
