name: Bug
description: Report a CVA6 RTL bug
title: "[BUG] <title>"
labels: ["Type:Bug"]
body:
- type: checkboxes
  attributes:
    label: Code of Conduct
    options:
    - label: I have searched the existing bug issues.
      required: true
    - label: >-
        I am a human engaging in an interpersonal interaction.
        During this interaction, my words are my own and are not generated.
        If relevant, I provide links to my sources.
      required: true
- type: textarea
  attributes:
    label: Bug Description
    value: |
      <!-- Introduction -->

      = Steps to reproduce

      == Expected behavior

      == Observed behavior

  validations:
    required: true
