name: CVA6 bug
description: Create a CVA6 bug
title: "[BUG] <title>"
labels: ["Type:Bug"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing CVA6 bug for this?
    description: Please search to see if an issue already exist for the bug you need to create
    options:
    - label: I have searched the existing bug issues
      required: true
- type: textarea
  attributes:
    label: Bug Description
    description: A concise description of the bug
  validations:
    required: true
