onerror {resume}
quietly WaveActivateNextPane {} 0
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/RT_DEPTH
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/rst_ni
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/N
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_valid_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_valid_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_rt_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_ready_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_ready_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_id_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_demux_valid
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_demux_sel
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_demux_ready
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/mem_resp_demux
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/i_mem_resp_read_demux/clk_i
add wave -divider demux
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/noc_req_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/noc_resp_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/ypb_load_req
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/ypb_load_rsp
add wave -divider d_cache
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/HPDCACHE_ENABLE_CMO
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/HPDCACHE_NREQUESTERS
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/NUM_SNOOP_PORTS
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/MMU_PTW_INDEX
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/ZCMT_INDEX
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/LOAD_INDEX
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/STORE_AMO_INDEX
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/CMO_INDEX
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/HWPF_INDEX
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/refill_core_rsp_valid
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/uc_core_rsp_ready
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/uc_core_rsp_valid
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/cmo_core_rsp_ready
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/cmo_core_rsp_valid
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/hpdcache_ctrl_i/st1_rsp_valid
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/core_rsp_valid
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_req_read_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_req_read_valid_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_req_read_ready_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_resp_read_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_resp_read_valid_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_resp_read_ready_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_resp_write_valid_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_resp_write_ready_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_resp_write_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_req_write_valid_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_req_write_ready_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_req_write_data_valid_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_req_write_data_ready_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/mem_req_write_data_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_hpdcache/core_rsp
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_req_valid
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_req_ready
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_req
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_req_abort
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_req_tag
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_req_pma
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_rsp_valid
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_rsp
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_read_miss
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/dcache_write_miss
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/mem_resp_read_valid_arb
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/mem_resp_read_ready_arb
add wave -expand -subitemconfig {{/uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/mem_resp_read_idext_arb[0]} -expand} /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/mem_resp_read_idext_arb
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/mem_req_read_valid_arb
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/mem_req_read_ready_arb
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/mem_req_read_idext_arb
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/mem_req_read_arb
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/icache_miss_valid_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/icache_miss_resp_valid_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/icache_miss_resp_ready_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/icache_miss_resp_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/icache_miss_ready_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/icache_miss_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/dcache_read_valid_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/dcache_read_resp_valid_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/dcache_read_resp_ready_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/dcache_read_resp_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/dcache_read_ready_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_axi_arbiter/dcache_read_i
add wave -divider load_cache
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_req_sid_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_store_req_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_store_rsp_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_amo_req_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_amo_rsp_o
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_load_req_i
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_load_rsp_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_mmu_ptw_req_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_mmu_ptw_rsp_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_zcmt_req_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/ypb_zcmt_rsp_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/cva6_dcache_flush_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/cva6_dcache_flush_ack_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_req_valid_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_req_ready_i
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_req_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_req_abort_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_req_tag_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_req_pma_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_rsp_valid_i
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_rsp_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/forward_store
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/forward_amo
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_req_is_uncacheable
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_load_if_adapter/hpdcache_req
add wave -divider load_unit
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/lsu_ctrl_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/pop_ld_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/valid_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/trans_id_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/result_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ex_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/translation_req_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/vaddr_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/tinst_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/hs_ld_st_inst_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/hlvx_inst_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/paddr_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ex_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/dtlb_hit_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/dtlb_ppn_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/page_offset_o
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/page_offset_matches_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/store_buffer_empty_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/commit_tran_id_i
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ypb_load_req_o
add wave -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ypb_load_rsp_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/dcache_wbuffer_not_ni_i
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_valid_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_valid_d
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_flushed_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_flushed_d
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_empty
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_full
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_free_index
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_w
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_w_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_windex
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_windex_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_r
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_rdata
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_rindex
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ldbuf_last_id_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/kill_req_d
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/kill_req_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/paddr_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/be_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/paddr
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/paddr_is_cacheable
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/paddr_is_cacheable_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/paddr_nonidempotent
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/not_commit_time
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/inflight_stores
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/stall_ni
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ypb_a_state_d
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ypb_a_state_q
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ex_s0
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/ex_s1
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/kill_s1
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/stall_ypb
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/stall_translation
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/data_req
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/data_rvalid
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/shifted_data
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/rdata_sign_bits
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/rdata_offset
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/rdata_sign_bit
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/rdata_is_signed
add wave /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/i_load_unit/rdata_is_fp_signed
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3614 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 200
configure wave -valuecolwidth 321
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {13650 ns}
