onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ypb_store_rsp_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ypb_store_req_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ypb_mmu_ptw_rsp_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ypb_mmu_ptw_req_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ypb_load_rsp_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ypb_load_req_o
add wave -noupdate -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ypb_amo_rsp_i
add wave -noupdate -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ypb_amo_req_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vsatp_ppn_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vs_sum_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vs_asid_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vmxr_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vmid_to_be_flushed_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vmid_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vaddr_xlen
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vaddr_to_be_flushed_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vaddr_to_be_flushed
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/vaddr_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/v_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/translation_valid
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/translation_req
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/tinst_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/sum_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/sum
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/store_valid_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/store_trans_id_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/store_result_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/store_exception_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/store_buffer_empty
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/stall_st_pending_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_valid_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_valid
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_vaddr
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_translation_req
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_trans_id
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_tinst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_result
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_hs_ld_st_inst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_hlvx_inst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/st_ex
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/satp_ppn_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/satp_ppn
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/rvfi_mem_paddr_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/rvfi_lsu_ctrl_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/rst_ni
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/priv_lvl_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/pop_st
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/pop_ld
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/pmpcfg_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/pmpaddr_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/pmp_translation_valid
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/pmp_fetch_arsp
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/pmp_exception
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/page_offset_matches
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/page_offset
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/overflow
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/no_st_pending_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/mxr_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/mxr
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/mmu_vaddr
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/mmu_tinst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/mmu_paddr
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/mmu_hs_ld_st_inst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/mmu_hlvx_inst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/mmu_exception
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/misaligned_exception
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/lsu_valid_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/lsu_req_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/lsu_ready_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/lsu_paddr
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/lsu_ctrl
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/load_valid_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/load_trans_id_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/load_result_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/load_exception_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_valid_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_valid
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_vaddr
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_translation_req
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_trans_id
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_tinst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_st_v_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_st_priv_lvl_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_result
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_hs_ld_st_inst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_hlvx_inst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/ld_ex
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/itlb_miss_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/hs_ld_st_inst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/hlvx_inst
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/hgatp_ppn_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/gpaddr_to_be_flushed_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/g_overflow
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/fu_data_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/flush_tlb_vvma_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/flush_tlb_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/flush_tlb_gvma_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/flush_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/fetch_vaddr_plen
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/fetch_arsp_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/fetch_areq_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/enable_translation_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/enable_g_translation_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/en_ld_st_translation_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/en_ld_st_g_translation_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/dtlb_ppn
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/dtlb_miss_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/dtlb_hit
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/dcache_wbuffer_not_ni_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/dcache_wbuffer_empty_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/data_misaligned
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/CVA6Cfg
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/csr_hs_ld_st_inst_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/commit_tran_id_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/commit_ready_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/commit_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/clk_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/be_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/asid_to_be_flushed_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/asid_to_be_flushed
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/asid_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/asid
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/ex_stage_i/lsu_i/amo_valid_commit_i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {11052 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 199
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {34 ns} {12892 ns}
