// N2D2 auto-generated file.
// @ Fri Sep 10 16:23:21 2021

#ifndef N2D2_EXPORTCPP_MEM_INFO_H
#define N2D2_EXPORTCPP_MEM_INFO_H

#define MEMORY_SIZE 2160
#define MEMORY_ALIGNMENT 1
#define ENV_MEM_SIZE 1
#define ENV_MEM_STRIDE 1
#define ENV_MEM_LENGTH 24
#define ENV_MEM_COUNT 24
#define ENV_MEM_CONT_OFFSET 0
#define ENV_MEM_CONT_SIZE 576
#define ENV_MEM_WRAP_OFFSET 0
#define ENV_MEM_WRAP_SIZE 0
#define CONV1_MEM_SIZE 16
#define CONV1_MEM_STRIDE 16
#define CONV1_MEM_LENGTH 11
#define CONV1_MEM_COUNT 11
#define CONV1_MEM_CONT_OFFSET 576
#define CONV1_MEM_CONT_SIZE 1584
#define CONV1_MEM_WRAP_OFFSET 0
#define CONV1_MEM_WRAP_SIZE 352
#define CONV2_MEM_SIZE 24
#define CONV2_MEM_STRIDE 24
#define CONV2_MEM_LENGTH 4
#define CONV2_MEM_COUNT 4
#define CONV2_MEM_CONT_OFFSET 352
#define CONV2_MEM_CONT_SIZE 384
#define CONV2_MEM_WRAP_OFFSET 0
#define CONV2_MEM_WRAP_SIZE 0
#define FC1_MEM_SIZE 150
#define FC1_MEM_STRIDE 150
#define FC1_MEM_LENGTH 1
#define FC1_MEM_COUNT 1
#define FC1_MEM_CONT_OFFSET 736
#define FC1_MEM_CONT_SIZE 150
#define FC1_MEM_WRAP_OFFSET 0
#define FC1_MEM_WRAP_SIZE 0
#define FC2_MEM_SIZE 10
#define FC2_MEM_STRIDE 10
#define FC2_MEM_LENGTH 1
#define FC2_MEM_COUNT 1
#define FC2_MEM_CONT_OFFSET 886
#define FC2_MEM_CONT_SIZE 10
#define FC2_MEM_WRAP_OFFSET 0
#define FC2_MEM_WRAP_SIZE 0

#endif
