# Copyright 2021 Thales DIS design services SAS
#
# Licensed under the Solderpad Hardware Licence, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
# You may obtain a copy of the License at https://solderpad.org/licenses/
#
# Original Author: Jean-Roch COULON (jean-roch.coulon@thalesgroup.fr)

# where are the tools
if ! [ -n "$RISCV" ]; then
  echo "Error: RISCV variable undefined"
  return
fi

if ! [ -n "$BBL_ROOT" ]; then
  echo "Error: BBL_ROOT variable undefined"
  echo "BBL_ROOT is the path to access bbl.o"
  echo "bbl.o is generated by using https://github.com/pulp-platform/ariane-sdk.git"
  return 1
fi

# install the required tools
source ./cva6/regress/install-cva6.sh
source ./cva6/regress/install-riscv-dv.sh

cd cva6/sim
cp $BBL_ROOT/bbl bbl.o
python3 cva6.py --target cv64a6_imafdc_sv39 --iss=veri-testharness-linux --iss_yaml=cva6.yaml --elf_tests bbl.o
cd -
