# Copyright 2026 Thales France
#
# Licensed under the Solderpad Hardware Licence, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
# You may obtain a copy of the License at https://solderpad.org/licenses/
#
# Original Author: Yannick Casamatta (yannick.casamatta@thalesgroup.com)

"""
Build manifest utilities.

Each recipe that generates artifacts in the build tree writes a
`cook_manifest.yml` file in its output directory. The manifest records the
recipe name and the options used to generate the artifacts.

Recipes that depend on those artifacts can then:
- check that the prerequisite artifacts exist and print an actionable
  message telling the user which recipe to run first (require_prerequisite)
- read the manifest and check that the options used by the producer recipe
  are compatible with the options requested now (require_manifest_option)
"""

from datetime import datetime
from enum import Enum
from pathlib import Path
import typer
import yaml
from flows.utils.utils import (
    print_error,
    print_warning,
    print_info,
)

MANIFEST_NAME = "cook_manifest.yml"


def _serialize(value):
    """Convert option values to plain YAML-friendly types."""
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (list, tuple)):
        return [_serialize(v) for v in value]
    if isinstance(value, dict):
        return {k: _serialize(v) for k, v in value.items()}
    return value


def write_manifest(out_dir, recipe, options, quiet=False):
    """
    Write the build manifest describing how `out_dir` was generated.

    Args:
        out_dir: output directory of the recipe (Path)
        recipe: cook.py recipe name (e.g. "vcs-uvm-comp")
        options: dict of the options used by the recipe
        quiet: suppress info output
    """
    manifest_path = Path(out_dir) / MANIFEST_NAME
    data = {
        "recipe": recipe,
        "date": datetime.now().isoformat(timespec="seconds"),
        "options": _serialize(options),
    }
    try:
        with manifest_path.open("w", encoding="utf-8") as f:
            yaml.safe_dump(data, f, sort_keys=False, default_flow_style=False)
        print_info(f"manifest written: {manifest_path}", quiet=quiet)
    except Exception as e:
        print_warning(f"Could not write manifest {manifest_path}: {e}")


def read_manifest(out_dir):
    """
    Read the build manifest of `out_dir`.

    Returns the manifest dict, or None if the manifest is missing or
    unreadable (e.g. artifacts generated by an older version of cook.py).
    """
    manifest_path = Path(out_dir) / MANIFEST_NAME
    if not manifest_path.exists():
        return None
    try:
        with manifest_path.open("r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    except Exception as e:
        print_warning(f"Could not read manifest {manifest_path}: {e}")
        return None


def require_prerequisite(path, description, hint):
    """
    Check that a prerequisite artifact exists.

    Exits with an actionable error message telling the user which recipe
    to run first if the artifact is missing.

    Args:
        path: artifact path expected to exist (file or directory)
        description: human-readable description of the artifact
        hint: example cook.py command generating the artifact
    """
    path = Path(path)
    if not path.exists():
        print_error(f"Missing prerequisite: {description}")
        print_error(f"  Expected: {path}")
        print_error(f"  Run first: {hint}")
        raise typer.Exit(code=1)


def get_manifest_option(manifest, option, default=None):
    """Return an option recorded in a manifest, or `default` if absent."""
    if not manifest:
        return default
    return manifest.get("options", {}).get(option, default)


def require_manifest_option(
    manifest,
    option,
    allowed,
    requirement,
    hint,
    manifest_dir=None,
):
    """
    Check that an option recorded in a producer manifest is compatible
    with the options requested now. Exits with an explanation if not.

    If the manifest is missing (artifacts generated by an older cook.py),
    only a warning is printed and the check is skipped.

    Args:
        manifest: manifest dict returned by read_manifest() (or None)
        option: option name recorded in the producer manifest
        allowed: list of accepted values for this option
        requirement: human-readable description of the incompatibility
        hint: example cook.py command fixing the problem
        manifest_dir: producer output dir (for warning message only)
    """
    if manifest is None:
        where = f" in {manifest_dir}" if manifest_dir else ""
        print_warning(
            f"No manifest found{where} (generated by an older cook.py?), skipping compatibility check for '{option}'"
        )
        return
    value = get_manifest_option(manifest, option)
    if value not in allowed:
        producer = manifest.get("recipe", "producer recipe")
        print_error(f"Incompatible option: {requirement}")
        print_error(
            f"  '{producer}' was run with {option}={value!r}, expected one of {[_serialize(a) for a in allowed]}"
        )
        print_error(f"  Fix: {hint}")
        raise typer.Exit(code=1)
