# Copyright 2026 Thales France
#
# Licensed under the Solderpad Hardware Licence, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
# You may obtain a copy of the License at https://solderpad.org/licenses/
#
# Original Author: Yannick Casamatta (yannick.casamatta@thalesgroup.com)

# Please refer to flows/README.md to add target


# ===========================================================================================

# THIS FILE NEED TO BE ADAPTED to fit your environment

# This is a dummy configuration file. You can modify it locally, and by default it is
# used by cook.py. However, it is mode convenient to use your own configuration directory
# by setting the CONFIG_DIR environment variable.

# see flows/utils/config_loader.py

# ===========================================================================================

dummy1: &dummy1
    TOOLS_PATH: "/tmp/llvm-20"
    CLANG: "riscv32-unknown-elf-clang"
    GCC: None
    OBJDUMP: "riscv32-unknown-elf-objdump"
    NM: "riscv32-unknown-elf-nm"
    TARGET_TOOLCHAIN: "riscv32-unknown-elf"

dummy2: &dummy2
    TOOLS_PATH: "/tmp/gcc-15"
    CLANG: None
    GCC: "riscv32-unknown-elf-clang"
    OBJDUMP: "riscv32-unknown-elf-objdump"
    NM: "riscv32-unknown-elf-nm"
    TARGET_TOOLCHAIN: "riscv32-unknown-elf"

my_cv32a60x_toolchain:
  <<: *dummy1
my_cv32a60x_no_zcmt_toolchain:
  <<: *dummy1
my_cv32a60x_axi_toolchain:
  <<: *dummy1
my_cv32a60x_no_zcmt_axi_toolchain:
  <<: *dummy1
my_cv32a65x_noPMP_toolchain:
  <<: *dummy1
my_cv32a65x_noPMP_axi_toolchain:
  <<: *dummy1
my_cv64a6_imafdc_sv39_hpdcache_nopmp_nommu_obi_toolchain:
  <<: *dummy1
my_cv64a6_imafdc_sv39_hpdcache_nopmp_nommu_axi_toolchain:
  <<: *dummy1
my_cv32a60x_zcmt_pmp_toolchain:
  <<: *dummy2
my_cv32a60x_zcmt_pmp_axi_toolchain:
  <<: *dummy2
my_cv32a65x_toolchain:
  <<: *dummy2
my_cv32a65x_axi_toolchain:
  <<: *dummy2
my_cv64a6_imafdc_sv39_hpdcache_pmp_nommu_obi_toolchain:
  <<: *dummy2
my_cv64a6_imafdc_sv39_hpdcache_pmp_nommu_axi_toolchain:
  <<: *dummy2
my_cv32a65x_sv32_toolchain:
  <<: *dummy2
my_cv32a65x_sv32_axi_toolchain:
  <<: *dummy2
my_cv32a6_imac_sv32_obi_toolchain:
  <<: *dummy2
my_cv32a6_imac_sv32_toolchain:
  <<: *dummy2
my_cv64a6_imafdc_sv39_hpdcache_pmp_mmu_obi_toolchain:
  <<: *dummy2
my_cv64a6_imafdc_sv39_hpdcache_pmp_mmu_axi_toolchain:
  <<: *dummy2
